### ISSUE TITLE
Making this work again?

### ISSUE THREAD

**Issue by ivanperez-keera** [uduki/hsQt#1]
I've been trying to make Qt bindings work in Haskell. (I am currently using QML.)

The berlios page is down. This is the only "fork" I've found.

Would it be possible to make this compile? In particular, is it possible to install in a cabal sandbox?

It doesn't find OpenGL (even though I did install it -- in a sandbox).

I realise that making this work again after 3 years may be non-trivial. Any help would be appreciated.

**Comment by ivanperez-keera** [comment]
Well, I forked and made it work. Feel free to pull or, if you don't want to maintain it, I'll push to the fork.

I had to modify build.pl to install this in a sandbox, but the changes are not (easily) portable :(

**Comment by uduki** [comment]
Oh! Great it work!

Now I don't maintain this repo, but I want to cooperate with your the working :)

**Comment by ivanperez-keera** [comment]
Ok. Feel free to jump in at any time.

In the short term, it would be great to simplify the installation, make it as standard as possible, so that we can upload it to hackage and others can just cabal install qt. That may get some people insterested, and they may be able to help.

In the long term, rethinking the API and having Qt 5 support would be great.

The current version at keera-studios compiles and works. I'm working on a reactive framework that connects to Qt (and wx, and gtk, and other backends).

I'm going to try to make some Haskell Qt program work on Android.

Closing this now.
